name: Update Playlist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  validate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for force push to work properly

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Check files before validation
        run: ls -R all_channels  # Debug step to check if files exist

      - name: Validate links
        run: cd all_channels && python link_validator.py

      - name: Update playlist
        run: cd all_channels && python playlist_completer.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          touch all_channels/tivimate_playlist.m3u8  # Ensure timestamp update
          git add --all
          git diff --staged --quiet || git commit -m "Force update playlist"
          git push --force

