name: Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  validate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for force push to work properly

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Validate links
        run: python all_channels/link_validator.py

      - name: Update playlist
        run: python all_channels/playlist_completor.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add all_channels/tivimate_playlist.m3u8
          # If there are no changes, the commit command will fail.
          # Using '|| echo "No changes to commit"' prevents the job from failing.
          git commit -m "Update playlist with validated links" || echo "No changes to commit"
          git push --force
